feedback2/feedback/urls.py
from django.conf.urls import url
from . import views

app_name = 'feedback'

urlpatterns = [
    url(r'^$', views.feedback_index, name = 'feedback_index'),
    url(r'^submit_feedback/$', views.submit_feedback, name = 'submit_feedback'),
]

feedback2/feedback2/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^feedback2/', include('feedback.urls'), name = 'feedback'),
    url(r'^$', views.index, name = 'home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedback2/feedback/models.py
from django.db import models

class UserFeedback(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    email = models.EmailField()
    phone = models.CharField(max_length = 13)
    message = models.CharField(max_length = 100)

    def __str__(self):
        return str(self.first_name)

feedback2/feedback/views.py
from django.shortcuts import render, redirect
from .models import UserFeedback
# Create your views here.

def feedback_index(request):
    if request.method == 'GET':
        return render(request, 'feedback/1.html')

def submit_feedback(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        phone_number = request.POST.get('phone_number')
        message = request.POST.get('message')
        if first_name and last_name and email and phone_number and message:
            feedback_obj = UserFeedback.objects.create()
            feedback_obj.first_name = first_name
            feedback_obj.last_name = last_name
            feedback_obj.email = email
            feedback_obj.phone = phone_number
            feedback_obj.message = message
            feedback_obj.save()
            return render(request, 'feedback/feedback_sent.html')
        else:
            redirect('/feedback_index/')

feedback2/feedback2/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'index.html')

feedback2/feedback/templates/feedback/1.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
       <title> Contact form Design</title>
       <style>
       body{
           margin: 0;
           padding:0;
           text-align:center;
           background: linear-gradient(rgba(0,0,50,0.5),rgba(0,0,50,0.5)),url("{% static 'feedback/1.jpg' %}");
           background-size:cover;
           background-position: center;


       }
       .contact-title
       {
           margin-top:100px;
           color:#fff;
           text-transform:uppercase;
           transition: all 4s ease-in-out;
       }
       .contact-title h1{
           font-size:32px;
           line-height: 10px;
       }
       form
       {
           margin-top: 50px;
           transition:all 4s ease-in-out;
       }
       .form-control
       {
           width:600px;
           background:transparent;
           border:none;
           outline:none;
           border-bottom: 1px solid gray;
           color:#fff;
           font-size:18px;
           margin-bottom: 16px;

       }

       input{
           height: 45px
       }
       form .submit
       {
           background:#ff5722;
           border-color:transparent;
           color:#fff;
           font-size:20px;
           font-weight:bold;
           letter-spacing: 2px;
           height: 50px;
           margin-top:20px;
       }
       form .submit:hover
       {
           background-color:#f44336;
           cursor:pointer;

       }
       </style>
</head>
<body style="background-image: ">
        <div class="contact-title">
            <h1>CONTACT US</h1>
        </div>
        <div class ="contact-form">
            <form id="contact-form" method="post" action="{% url 'feedback:submit_feedback' %}">
              {% csrf_token %}
                <input name= "first_name" type="text" class="form-control" placeholder="First Name" required><br>
                <input name= "last_name" type="text" class="form-control" placeholder="Last Name" required><br>
                <input name="email" type="email" class="form-control" placeholder="Email" required><br>
                <input name="phone_number" type="Phone" class="form-control" placeholder="Phone Number" required><br>
               <textarea style="height: 80px;" class="form-control" placeholder="Message" row="16" required name="message"></textarea><br>
               <input type="submit" class="form-control submit" value="SEND MESSAGE">
            </form>
        </div>
        
</body>
</html>

feedback2/feedback/templates/feedback/feedback_sent.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Feedback Sent</title>
  </head>
  <body>
    <p>Feedback Sent</p>
  </body>
</html>

feedback2/templates/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
    <style media="screen">
    ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover {
  background-color: #111;
}
    </style>
  </head>
  <body>
    <ul>
  <li><a class="active" href="{% url 'feedback:feedback_index' %}">Feedback</a></li>
</ul>
    <p>Welcome to the homepage.</p>
  </body>
</html>